### PR TITLE
fix tests that reference map and refactor

### LINKED ISSUE #42: fix testing issues
new map creation interview with map-blueprint broke stuff

### PR DESCRIPTION
**Pull request by saylerb**
- fixing testing referencing map
  - we changed the interface of map to construct the map based on
    a map-blueprint
  - I modified these tests which instantiated a map object to take in a blueprint
    - player-test
    - map-test
- add a before action to the player-test
- move barrier definitions to map blueprint class
- add acceleration as a property of player
- add default acceleration of 0.1 to player options constructor
- some refactoring of Player class

closes #42

### CODE REVIEW

File: lib/map-blueprint.js [hunk 1]
```diff
@@ -12,12 +14,15 @@ export default class MapBlueprint {
...
+      barriers: this.barriers,
       columns: 8,
       rows: 8,
       blueFlagOptions: { color: 'blue', x: 150, y: 150, tsize: this.tsize },
       redFlagOptions: { color: 'red', x: 250, y: 250, tsize: this.tsize },
-      bluePlayerOptions: { x: 150, y: 150, color: 'blue', controls: 'wasd' },
-      redPlayerOptions:  { x: 100, y: 100, color: 'red', controls: 'arrows' }
+      bluePlayerOptions: { x: 150, y: 150, color: 'blue', 
+                           controls: 'wasd', acceleration: 0.1 },
+      redPlayerOptions:  { x: 100, y: 100, color: 'red',
```
Comment (robbiejaeger) [inline lib/map-blueprint.js:24]: Seems a little weird that acceleration would be defined in the map blueprint.

Comment (saylerb) [reply lib/map-blueprint.js:24]: Yeah, I thought maybe if we changed to an attribute of player (e.g. We made power ups that increased/decreased acceleration) then it should be defined. But in that case we should probably just default it 0.1 and not define it in the blueprint. Premature optimization ...
